# Generated by Django 2.1.7 on 2019-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzashop',
            name='addres',
        ),
        migrations.AddField(
            model_name='pizzashop',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
