# Generated by Django 2.1.7 on 2019-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0003_auto_20190312_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
