# Generated by Django 2.1.7 on 2019-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0004_auto_20190313_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='address',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
